fn main(a: pub u128, mut b: i8) -> return_data i8 {
    let mut ctx_limit: u32 = 25_u32;
    b = {
        for idx_c in 64_i8 .. 71_i8 {
            b = {
                let d = b;
                match d {
                    73 => (((a as i64) >> (b as i64)) as i8),
                    _ => {
                        unsafe { func_1_proxy(((293314063872897542864337424628711804185_u128, if ((idx_c as i16) > (idx_c as i16)) {
                            a
                        } else {
                            a
                        }, (idx_c - idx_c), {
                            let e = a;
                            match e {
                                64710361849160893222746205103516844584 => {
                                    let f = a;
                                    match f {
                                        
                                        _ => a,
                                    }
                                },
                                _ => 199081901594038550120744428324523657143_u128,
                            }
                        }), 100720850477572403499874163295582491618, (b as i64), a, 203_u8), (a, 22625256307860138642649879313934018670_u128, -61_i8, 142771976980942551115244820456752509221_u128), 200439577271020524532941738180510872545, ctx_limit) }
                    },
                }
            };
            b = b;
        };
        b
    };
    b
}
unconstrained fn func_1(a: ((u128, u128, i8, u128), Field, i64, u128, u8), b: (u128, u128, i8, u128), mut c: Field, _ctx_limit: &mut u32) -> i8 {
    let d = b;
    match d {
        (item_e, item_f, item_g, item_h) => {
            let i = b;
            match i {
                (item_j, item_k, item_l, item_m) => {
                    {
                        let mut idx_n: u32 = 0_u32;
                        loop {
                            if (idx_n == 8_u32) {
                                break
                            } else { () }
                        }
                    };
                    a.0.2
                },
            }
        },
    }
}
unconstrained fn func_1_proxy(a: ((u128, u128, i8, u128), Field, i64, u128, u8), b: (u128, u128, i8, u128), mut c: Field, mut ctx_limit: u32) -> i8 {
    func_1(a, b, c, (&mut ctx_limit))
}

